<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
        <Configurations>Release;Debug</Configurations>
        <Platforms>AnyCPU</Platforms>
        <NoWarn>NU1701;CS8618</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MessagePack" Version="3.1.9"/>
    </ItemGroup>

</Project>
